USE DB_T04301_PAULO_SOSA;

CREATE TABLE TB_PRODUTOS (
	PRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRD_NOME VARCHAR(30),
    PRD_VALOR decimal(5,2),
    PRD_FABRICANTE VARCHAR(50)
);

CREATE TABLE TB_VENDAS (
	VEN_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEN_DATA DATE,
    VEN_PROD INT,
    VEN_CLIENTE INT,
    VEN_VALOR decimal(5,2)
);
;

CREATE TABLE TB_CLIENTES(
	CLI_ID int AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(30),
    CLI_ENDERECO VARCHAR(50),
    CLI_NASC date
);

INSERT INTO TB_PRODUTOS(PRD_NOME,PRD_VALOR,PRD_FABRICANTE)
	VALUES
	("PAPEL A4",30,"PAPEL"),
	('CANETA',5,'BIC'),
	('LÁPIS',5,'FABER')
;

INSERT INTO TB_CLIENTES (CLI_NOME,CLI_ENDERECO,CLI_NASC)
	VALUES
		('PAULO','TUCURUVI','1972-03-05'),
        ('IVA','TUCURUVI','1964/12/03'),
        ('DANIEL','VILA GUSTAVO','1995/03/04'),
        ('CHRIS','VILA GUSTAVO','1997/05/04')
;


SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_CLIENTES 
	WHERE CLI_ENDERECO LIKE 'VILA%';
    
SELECT * FROM TB_CLIENTES WHERE month(CLI_NASC)='03';
