use DB_T04301_PAULO_SOSA;

/* tarefa    */
  
  CREATE TABLE TB_CONTATOS (
		CONT_ID	INT auto_increment PRIMARY KEY,
        CONT_NOME VARCHAR(50) NOT NULL,
        CONT_EMAIL VARCHAR(50),
        CONT_GRUPO INT NOT NULL,
        foreign key (CONT_GRUPO) REFERENCES TB_GRUPOCONTATO(GCON_ID));
        
	CREATE TABLE TB_GRUPOCONTATO(
		GCON_ID INT PRIMARY KEY AUTO_INCREMENT,
        GCON_TIPO VARCHAR(50) NOT NULL);
		
	CREATE TABLE TB_TELEFONES(
		TELS_ID INT auto_increment PRIMARY KEY,
        TELS_TELEFONE VARCHAR(11) NOT NULL,
        TELS_CONTATO INT NOT NULL);
        

ALTER TABLE TB_TELEFONES ADD CONSTRAINT TB_TELEFONES_FK
	   FOREIGN KEY (TELS_CONTATO) REFERENCES TB_CONTATOS(CONT_ID);

INSERT INTO TB_GRUPOCONTATO(GCON_TIPO)
	VALUES 
		('FAMILIA'),
        ('ESCRITÓRIO'),
        ('AMIGOS'),
        ('CREDORES');
        
SELECT * FROM TB_GRUPOCONTATO;

INSERT INTO TB_CONTATOS(CONT_NOME,CONT_EMAIL,CONT_GRUPO)
	VALUES
		('PAULO','',1),
        ('IVA','',1),
        ('FABIO','NADA',3),
        ('VISA','NÃO SEI',4),
        ('PEDRO','PEIXINHO',2);

SELECT * FROM TB_CONTATOS;
SELECT CONT_EMAIL FROM TB_CONTATOS WHERE CONT_NOME LIKE 'PEDRO';


INSERT INTO TB_TELEFONES(TELS_TELEFONE,TELS_CONTATO)
	VALUES
			('11123456789',1),
            ('12345678901',1),
            ('32165462165',2),
            ('56526532256',5);

SELECT * FROM TB_TELEFONES;
        
