use DB_T04301_PAULO_SOSA;


CREATE TABLE TB_CONTATOS (
	COT_ID INT primary KEY auto_increment, 
    COT_NOME varchar(50),
    COT_TELEFONE VARCHAR(20),
    COT_ATIVO INT NOT NULL);

describe TB_CONTATOS;

alter TABLE TB_CONTATOS
	CHANGE COLUMN COT_TELEFONE COT_CELULAR varchar(20) NOT NULL;
    
  alter table TB_CONTATOS
	change column cot_ativo COT_ATIVO int;

alter table TB_CONTATOS
	drop column COT_ATIVO;

DROP TABLE TB_CONTATOS;







-- CARREGAR ARQUIVOS
 
-- CRIAR A TABELA DE ALUNOS

CREATE TABLE TB_ALUNOS_CARGA_DADOS (

	nome VARCHAR(50),

    idade INT

);
 
-- CONSULTA A TABELA

SELECT * FROM TB_ALUNOS_CARGA_DADOS;
 
-- REALIZANDO A CARGA DE DADOS NA TABELA

LOAD DATA LOCAL INFILE 'E:/Base_Pessoas_SQL.csv'

INTO TABLE TB_ALUNOS_CARGA_DADOS

FIELDS TERMINATED BY ';'

ENCLOSED BY '"'

LINES TERMINATED BY '\n'

IGNORE 1 ROWS;
 
 