USE DB_T04301_PAULO_SOSA;

CREATE TABLE TB_PAD_FORNECEDORES(
	FOR_ID int AUTO_INCREMENT PRIMARY KEY,
    FOR_NOME VARCHAR(50) NOT NULL,
    FOR_CNPJ VARCHAR(14),
    FOR_TEL VARCHAR(11)
);

CREATE TABLE TB_PAD_PRODUTOS (
	PRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRD_NOME VARCHAR(50) NOT NULL,
    PRD_VALOR decimal(8,2) NOT NULL,
    PRD_FABRICANTE INT NOT NULL,
    foreign key (PRD_FABRICANTE) REFERENCES TB_PAD_FORNECEDORES(FOR_ID)
);

CREATE TABLE TB_PAD_VENDAS (
	VEN_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEN_DATA DATE NOT NULL,
    VEN_PROD INT NOT NULL,
    VEN_QUANT INT NOT NULL,
    FOREIGN KEY (VEN_PROD) REFERENCES TB_PAD_PRODUTOS(PRD_ID)
);

INSERT INTO TB_PAD_FORNECEDORES(FOR_NOME,FOR_CNPJ,FOR_TEL)
	values
('Casa Pao de Qeuijo','12345678901234',''),
('Rei do Mate','12123123123412','12123123123'),
('Vega','12568985000125','11359968586')
;



INSERT INTO TB_PAD_PRODUTOS(PRD_NOME,PRD_VALOR,PRD_FABRICANTE)
	VALUES
	("Geléia Morango",30,3),
	('Mate Verde',5,2),
	('Pão de Queijo',5,1)
;



INSERT INTO TB_PAD_VENDAS(VEN_DATA,VEN_PROD,VEN_QUANT)
	VALUES
('2026-06-17',1,15),
('2026-06-17',2,3),
('2026-06-17',3,10)
;


SELECT * FROM TB_PAD_FORNECEDORES;
SELECT * FROM TB_PAD_PRODUTOS ;
SELECT * FROM TB_PAD_VENDAS;

