use DB_T04301_PAULO_SOSA;

create table LIVROS (
	LIV_ID INT  AUTO_INCREMENT PRIMARY KEY,
    LIV_TITULO VARCHAR(100) NOT NULL,
    LIV_AUTOR VARCHAR(80) NOT NULL,
    LIV_ANO_PUBLICACAO INT,
    LIV_GENERO VARCHAR(50)
);	

rename table LIVROS to TB_LIVROS;

insert into TB_LIVROS (LIV_TITULO,LIV_AUTOR,LIV_ANO_PUBLICACAO,LIV_GENERO)
	VALUES 
    ("Christine","Stephen King",2000,"Terror"),
    ("Sem título","Eu",2026,"Mistério")
;

SELECT * FROM TB_LIVROS
WHERE LIV_GENERO='TERROR'
order by
LIV_GENERO DESC;

SELECT * FROM TB_LIVROS
WHERE LIV_TITULO LIKE '%TIT%';

SELECT * FROM TB_LIVROS
WHERE LIV_TITULO LIKE '__m%';